[package]
name = "fte-protocols"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
fte-types = { path = "../fte-types" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
