/** Structural registry checks only: no Tauri generator, compiler or native execution. */
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
const root = fileURLToPath(new URL('../../../', import.meta.url));
const plugin = resolve(root, 'crates/tauri-plugin-loom');
const application = resolve(root, 'apps/loom/src-tauri');
const text = (base, path) => readFileSync(resolve(base, path), 'utf8');
const json = (base, path) => JSON.parse(text(base, path));
function constants(value, name, found = []) {
  if (value && typeof value === 'object') {
    if (value.const === name) found.push(value);
    for (const child of Object.values(value)) constants(child, name, found);
  }
  return found;
}
test('material rename has one owning native command and invoke registration', () => {
  assert.equal(text(plugin, 'build.rs').match(/"material_rename"/gu)?.length, 1);
  assert.equal(text(plugin, 'src/lib.rs').match(/material_commands::material_rename/gu)?.length, 1);
  assert.equal(text(plugin, 'src/material_commands.rs').match(/async fn material_rename\(/gu)?.length, 1);
  assert.match(text(plugin, 'src/lib.rs'), /#!\[forbid\(unsafe_code\)\]/u);
});
test('generated rename permissions mirror the owning command and are included by the default capability', () => {
  const expected = text(plugin, 'permissions/autogenerated/commands/material_set_pinned.toml')
    .replaceAll('material_set_pinned', 'material_rename').replaceAll('material-set-pinned', 'material-rename');
  assert.equal(text(plugin, 'permissions/autogenerated/commands/material_rename.toml'), expected);
  assert.equal(text(plugin, 'permissions/default.toml').match(/"allow-material-rename"/gu)?.length, 1);
  const acl = json(application, 'gen/schemas/acl-manifests.json').loom;
  assert.equal(acl.default_permission.permissions.filter(name => name === 'allow-material-rename').length, 1);
  for (const action of ['allow', 'deny']) {
    const permission = acl.permissions[`${action}-material-rename`];
    assert.equal(permission.identifier, `${action}-material-rename`);
    assert.deepEqual(permission.commands[action], ['material_rename']);
    assert.deepEqual(permission.commands[action === 'allow' ? 'deny' : 'allow'], []);
  }
  assert(json(application, 'gen/schemas/capabilities.json')['desktop-default'].permissions.includes('loom:default'));
});
test('plugin and desktop permission schemas each expose exactly one allow and deny constant', () => {
  for (const [base, path, prefix] of [
    [plugin, 'permissions/schemas/schema.json', ''],
    [application, 'gen/schemas/desktop-schema.json', 'loom:'],
    [application, 'gen/schemas/macOS-schema.json', 'loom:']
  ]) {
    const schema = json(base, path);
    for (const action of ['allow', 'deny']) {
      const entries = constants(schema, `${prefix}${action}-material-rename`);
      assert.equal(entries.length, 1, `${path} ${action}`);
      assert(entries[0].description.includes('material_rename'));
    }
    const defaults = constants(schema, `${prefix}default`);
    assert.equal(defaults.length, 1);
    assert(defaults[0].description.includes('`allow-material-rename`'));
  }
  const reference = text(plugin, 'permissions/autogenerated/reference.md');
  assert.equal(reference.match(/`loom:allow-material-rename`/gu)?.length, 1);
  assert.equal(reference.match(/`loom:deny-material-rename`/gu)?.length, 1);
});
