[package]
name = "mom-llama-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
mom-llama-runtime = { path = "../mom-llama-runtime" }
llama-native-types = { path = "../llama-native-types" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
uuid.workspace = true

[lints]
workspace = true
