[package]
name = "platform-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
attachment-native-host.workspace = true
fte-router.workspace = true
information-native-host.workspace = true
llama-native-host.workspace = true
llama-native-types.workspace = true
speech-native-host.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
