[package]
name = "loom-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "loom_app_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "loom"
path = "src/main.rs"

[build-dependencies]
loom-types = { path = "../../../crates/loom-types" }
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
loom-types = { path = "../../../crates/loom-types" }
tauri = { version = "2.11.5", features = [] }
tauri-plugin-dialog = "2.7.2"
tauri-plugin-loom = { path = "../../../crates/tauri-plugin-loom" }

[lints]
workspace = true
