[package]
name = "fte-router"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
fte-types = { path = "../fte-types" }
tokio.workspace = true

[dev-dependencies]
async-trait.workspace = true

[lints]
workspace = true
